const PHYSICAL_ATTACK = 1,
    MAGICAL_ATTACK = 2,
    DODGE = 1,
    PROTECTION = 2,
    ATTACK = 1,
    DEFENSE = 2;

module.exports = {
    PHYSICAL_ATTACK, MAGICAL_ATTACK, DODGE, PROTECTION, ATTACK, DEFENSE,
}
