const quotes = [
    'Mastering others is strength. Mastering yourself is true power.',
    'To the mind that is still, the whole universe surrenders.',
    'When I let go of what I am, I become what I might be.',
    'Nature does not hurry, yet everything is accomplished.',
    'Being deeply loved by someone gives you strength, while loving someone deeply gives you courage.',
    'He who knows, does not speak. He who speaks, does not know.',
    'When you are content to be simply yourself and don\'t compare or compete, everybody will respect you.',
    'The soft overcomes the hard; and the weak the strong.',
    'Silence is a source of great strength.',
    'If you correct your mind, the rest of your life will fall into place.',
    'The best fighter is never angry.',
    'A man with outward courage dares to die: a man with inner courage dares to live.',
    'A journey of a thousand miles begins with a single step.',
    'Knowing others is wisdom, knowing yourself is enlightenment.',
    'Care about what other people think and you will always be their prisoner.',
    'Mastering others is strength, mastering yourself is true power.',
    'If you do not change direction, you may end up where you are heading.',
    'Stop thinking and end your problems.',
    'New beginnings are disguised as painful endings.',
    'Manifest plainness, embrace simplicity, reduce selfishness, have few desires.',
    'Make your heart like a lake with a calm still surface and great depths of kindness.',
    'Great acts are made up of small deeds.',
    'He who is contented is rich.',
    'When I let go of what I am, I become what I might be.',
    'To a mind that is still, the whole universe surrenders.',
    'The heart that gives, gathers.',
    'Confidence is the greatest friend.',
    'When you are content to be simply yourself and don’t compare or compete, everybody will respect you.',
    'Silence is a source of great strength.',
    'Be still like a mountain, and flow like a great river.',
    'Act without expectation.',
    'Use the light that is within you to revert to your natural clearness of sight.',
    'Give a man a fish and you feed him for a day. Teach a man to fish and you feed him for a lifetime.',
    'Knowledge is a treasure, but practice is the key to it.',
    'Health is the greatest possession.',
    'Empty yourself of everything – let the mind become still.',
    'By letting go, it all gets done.',
];

module.exports = () => quotes[Math.floor(Math.random() * quotes.length)];
